trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  DOTNET_VERSION: '8.0.x'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '$(DOTNET_VERSION)'

- script: dotnet --version
  displayName: 'Check .NET SDK Version'

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.8.0'

- script: |
    echo "Restoring NuGet packages..."
    dotnet restore ToolsQA.sln --configfile nuget.config
  displayName: 'Restore NuGet Packages'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'ToolsQA.sln'
    arguments: '--configuration Release --verbosity minimal'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'ToolsQA.sln'
    arguments: '--configuration Release --logger trx --verbosity minimal'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/TestResults/*.trx'
    mergeTestResults: true
    failTaskOnFailedTests: true